version: "3.8"

services:
  nginx:
    container_name: dochub
    image: dochub
    build:
      context: .
      dockerfile: Dockerfile
      target: nginx
    ports:
      - "8080:8080"


  plantuml:
    image: ghcr.io/rabotaru/dochub/plantuml:v0.0.2
    container_name: plantuml
    ports:
      - "8079:8080"
