version: "3.8"

services:
  frontend:
    image: gchr.io/rabotaru/dockhub/frontend
    container_name: dockhub-frontend
    environment:
      VUE_APP_PLANTUML_SERVER: localhost:8079/svg/
    ports:
      - 8080:8080


  plantuml:
    image: gchr.io/rabotaru/dockhub/plantuml
    container_name: dockhub-plantuml
    ports:
      - 8079:8080
