version: "3.8"

services:
  dochub:
    image: ghcr.io/rabotaru/dochub:v2.0.0-rc1
    container_name: dochub
    environment:
      VUE_APP_PLANTUML_SERVER: localhost:8079/svg/
    ports:
      - 8080:8080


  plantuml:
    image: ghcr.io/rabotaru/dochub/plantuml:v0.0.2
    container_name: plantuml
    ports:
      - 8079:8080
