version: "3.8"

services:
  dochub:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    volumes:
    - ./:/var/www
    container_name: dochub
    environment:
      VUE_APP_PLANTUML_SERVER: localhost:8079/svg/
    ports:
      - 8080:8080
